version: '3.8'

services:
  app:
    image: mfo-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mfo-network

networks:
  mfo-network:
    driver: bridge
