spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mfodb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog/master.yaml
    enabled: true

server:
  port: 8080
